---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-checkout
spec:
  params:
    - name: repo-url
      value: https://github.com/vzaicevs/wtecc-CICD_PracticeCode.git
  serviceAccountName: tekton-robot
  taskRef:
    name: checkout
  workspaces:
    - name: appdir
      emptyDir: {}