---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-test-image
spec:
  steps:
    - name: build-test-image
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--context=git://github.com/vzaicevs/wtecc-CICD_PracticeCode.git"
        - "--dockerfile=./cicd/docker/test/Dockerfile"
        - "--destination=vzaicevs/demo:test-v1"
  workspaces:
    - name: docker-auth
      description: |
        Authentication data to push image to the registy
      mountPath: /kaniko/.docker/
