---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  steps:
    - name: build-docker-image
      image: gcr.io/kaniko-project/executor:latest
      #command: [/bin/sh]
      args:
        - "--context=git://github.com/vzaicevs/wtecc-CICD_PracticeCode.git"
        - "--dockerfile=./cicd/docker/base/Dockerfile"
        - "--destination=vzaicevs/demo:prod-v1"
  workspaces:
    - name: docker-auth
      description: |
        Authentication data to push image to the registy
      mountPath: /kaniko/.docker/
