---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
spec:
  workspaces:
    - name: docker-auth
    - name: appdir
  params:
    - name: repo-url
    - name: branch
  tasks:
    # - name: build-base-image
    #   taskRef:
    #     name: build-base-image
    #   workspaces:
    #     - name: docker-auth
    #       workspace: docker-auth
    # - name: build-test-image
    #   taskRef:
    #     name: build-test-image
    #   workspaces:
    #     - name: docker-auth
    #       workspace: docker-auth
    #   runAfter:
    #     - build-base-image
    - name: clean-appdir
      taskRef:
        name: clean-appdir
      workspaces:
        - name: appdir
          workspace: appdir
    - name: checkout
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: revision
          value: "$(params.branch)"
      workspaces:
        - name: output
          workspace: appdir
      runAfter:
        - clean-appdir
        # - build-test-image
    - name: lint
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: appdir
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value: ["--count","--max-complexity=10","--max-line-length=127","--statistics"]
      runAfter:
        - checkout
    - name: tests
      taskRef:
        name: tests
      workspaces:
        - name: appdir
          workspace: appdir
      runAfter:
        - checkout
      
