---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: echoer-pipeline
spec:
  params:
    - name: message
  tasks:
    - name: echoer
      taskRef:
        name: echoer
      params:
        - name: message
          value: "$(params.message)"
